### ISSUE TITLE
Could support setRequestHeader?

### ISSUE THREAD

**Issue by ZekeXu** [ckeditor/ckeditor5-adapter-ckfinder#14]
https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/0e5585387a18c7cb139d1fc701c55fa930014a72/src/uploadadapter.js#L129

My website configs with authorization header, so could you support this feature?
Thx

**Comment by Reinmar** [comment]
cc @Mgsy

**Comment by Mgsy** [comment]
Hi @ZekeXu, are you using CKFinder for uploading images? This repository contains the upload adapter for CKFinder, if you want to create your own adapter, take a look at our [custom image upload adapter guide](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/deep-dive/upload-adapter.html).

**Comment by ZekeXu** [comment]
Very powerful. Thank you @Mgsy , i will write a plugin by the docs.

**Comment by Ruud-cb** [comment]
@Mgsy I see this is a similar question to #10, I just posted a comment there about Reinmar's response but yours appears to be the same. I don't want to create my own adapter, I just want to add a header, why is it so difficult to implement?

https://github.com/ckeditor/ckeditor5-adapter-ckfinder/issues/10#issuecomment-487366977

**Comment by qqaimh** [comment]
Maybe the idea is good. However, if they support the feature , it may bring some safe questions, 

> @Mgsy I see this is a similar question to #10, I just posted a comment there about Reinmar's response but yours appears to be the same. I don't want to create my own adapter, I just want to add a header, why is it so difficult to implement?
> 
> [#10 (comment)](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/issues/10#issuecomment-487366977)

Maybe the idea is good. However, if they support the feature , it may bring some safe questions,

**Comment by qqaimh** [comment]
> @Mgsy I see this is a similar question to #10, I just posted a comment there about Reinmar's response but yours appears to be the same. I don't want to create my own adapter, I just want to add a header, why is it so difficult to implement?
> 
> [#10 (comment)](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/issues/10#issuecomment-487366977)
Maybe the idea is good. However, if they support the feature , it may bring some safe questions,

**Comment by Ruud-cb** [comment]
@qqaimh could you elaborate?

**Comment by qqaimh** [comment]
> elaborate

I have give up to use the series of ckeditor, As I am using Angular, I think they are so trouble to combine with Angular.

**Comment by Ruud-cb** [comment]
I also use it with angular, other then typescript typings would be great, the library works fine with Angular 7 imho. I hoped you woul elaborate on the 'safe questions?'

**Comment by qqaimh** [comment]
> I also use it with angular, other then typescript typings would be great, the library works fine with Angular 7 imho. I hoped you woul elaborate on the 'safe questions?'

In my opinion,If it support setRequestHeader ,it may be easily used  to evil upload something to server by someone. like set a jwt token

**Comment by sshaw** [comment]
The default adapter should allow one to set headers and reformat the response body to conform to the file manager's specification. These are the most common operations one will have to do. Having to rollout a custom uploader and a plugin for this that will reimplement 98% of the code contained in the out the box implementation should not be necessary. This is a somewhat unfriendly API. 
 
At minimum [`UploadAdapter`](https://github.com/ckeditor/ckeditor5-adapter-ckfinder/blob/151a0524cfbca0a70c6238019f12988d7a24ffdb/src/uploadadapter.js) should be made public so one can override `upload` and `sendRequest`. But, this is not as ideal as having these options out of the box. 

With TinyMCE I can just say ` images_upload_handler: uploadFunction`. Very easy.
